{{- if eq .Values.config.RUN_AS_DAEMON "false" }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "mongodb-backup-aws.fullname" . }}
  labels:
    {{- include "mongodb-backup-aws.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.config.CRON_SCHEDULE }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            # command: ["/bin/bash", "-c", "/etl/bash/copy_mongo_to_postgres.sh"]
            envFrom:
            - configMapRef:
                name: {{ include "mongodb-backup-aws.fullname" . }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: Never
{{- end }}
